import{a as b,S,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const v="52370866-f56fe6e7c04694f1b916d2ffa",R="https://pixabay.com/api/",q=15;async function $(s,r=1){const t={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:r};try{return(await b.get(R,{params:t})).data}catch(n){throw new Error("Error fetching images: "+n.message)}}const f=document.querySelector(".gallery"),y=document.querySelector(".load-more"),g=document.querySelector(".loader");let h=new S(".gallery a",{captionsData:"alt",captionDelay:250});function E(){f.innerHTML="",h.refresh()}function P(s){const r=s.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <div class="info">
        <p><span>Likes</span>${t.likes}</p>
        <p><span>Views</span>${t.views}</p>
        <p><span>Comments</span>${t.comments}</p>
        <p><span>Downloads</span>${t.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),h.refresh()}function B(){g.style.display="block"}function m(){g.style.display="none"}function H(){y.style.display="inline-block"}function p(){y.style.display="none"}function M(){const s=f.querySelector(".gallery-item");return s?s.getBoundingClientRect().height:0}const w=document.querySelector(".form"),A=w.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let c="",l=1,i=0,d=0;p();w.addEventListener("submit",async s=>{s.preventDefault();const r=A.value.trim();if(!r){a.error({message:"Please enter a search term!",position:"topRight",class:"custom-toast custom-error"});return}r!==c&&(c=r,l=1,i=0,d=0,E(),p()),await L({initial:!0})});O.addEventListener("click",async()=>{l+=1,await L({smoothScroll:!0})});async function L({initial:s=!1,smoothScroll:r=!1}={}){try{B();const t=await $(c,l),{hits:n,totalHits:e}=t;if(l===1&&n.length===0){m(),a.warning({message:"Sorry, no images found!",position:"topRight",class:"custom-toast custom-warning"});return}if(P(n),i=e,d+=n.length,d>=i?(p(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):H(),r){const o=M();o>0&&window.scrollBy({top:o*2,behavior:"smooth"})}s&&a.success({message:`Found ${i} images for "${c}"`,position:"topRight"})}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight",class:"custom-toast custom-error"})}finally{m()}}
//# sourceMappingURL=index.js.map
